import os
import cv2
import numpy as np
from pathlib import Path

def generate_ad_heatmaps_v2(original_dir, mask_dir, output_dir, item_list, alpha=0.5):
    """
    original_dir: The total folder containing the original input large images
    mask_dir: The total folder of 224x224 grayscale images generated by the network
    output_dir: The total folder where the final 224x224 heatmaps are saved
    item_list: The list of categories to be traversed
    alpha: The transparency weight of the original image (0.0 - 1.0)
    """
    orig_base = Path(original_dir)
    mask_base = Path(mask_dir)
    out_base = Path(output_dir)
    
    valid_extensions = {'.jpg', '.jpeg', '.png', '.bmp', '.tiff', '.webp'}
    target_size = (224, 224) 
    
    processed_count = 0
    missing_count = 0

    for item in item_list:
        test_dir = orig_base / item / 'test'
        
        if not test_dir.exists() or not test_dir.is_dir():
            continue

        for category_dir in test_dir.iterdir():
            if not category_dir.is_dir() or category_dir.name == 'good':
                continue

            for orig_img_path in category_dir.iterdir():
                if orig_img_path.suffix.lower() in valid_extensions:
                    
                    # 1. 计算相对路径并对齐
                    relative_path = orig_img_path.relative_to(orig_base)
                    mask_img_path = mask_base / relative_path
                    final_out_path = out_base / relative_path
                    
                    if not mask_img_path.exists():
                        print(f"Warning: Unable to find the corresponding network output -> {mask_img_path}")
                        missing_count += 1
                        continue

                    orig_img = cv2.imread(str(orig_img_path), cv2.IMREAD_COLOR)
                    mask_img = cv2.imread(str(mask_img_path), cv2.IMREAD_GRAYSCALE)
                    
                    if orig_img is None or mask_img is None:
                        continue

                    orig_img_resized = cv2.resize(orig_img, target_size, interpolation=cv2.INTER_AREA)

                    mask_img_resized = cv2.resize(mask_img, target_size, interpolation=cv2.INTER_NEAREST)

                    heatmap = cv2.applyColorMap(mask_img_resized, cv2.COLORMAP_JET)

                    overlay = cv2.addWeighted(orig_img_resized, alpha, heatmap, 1 - alpha, 0)

                    os.makedirs(os.path.dirname(final_out_path), exist_ok=True)
                    cv2.imwrite(str(final_out_path), overlay)
                    
                    processed_count += 1

    print(f"Processing completed! Successfully generated and saved {processed_count} 224x224 fused heat maps.")

if __name__ == "__main__":

    item_list = ['carpet', 'grid', 'leather', 'tile', 'wood', 'bottle', 'cable', 'capsule',
                 'hazelnut', 'metal_nut', 'pill', 'screw', 'toothbrush', 'transistor', 'zipper']
    # item_list = ['candle', 'capsules', 'cashew', 'chewinggum', 'fryum', 'macaroni1', 'macaroni2',
                # 'pcb1', 'pcb2', 'pcb3', 'pcb4', 'pipe_fryum']
    # item_list = ['01', '02', '03']

    original_folder = "../mvtec_anomaly_detection"
    # original_folder = "../VisA_pytorch/1cls"
    # original_folder = "../BTech_Dataset_transformed"

    mask_folder = "./MVTec_AnoMaps"       # AnoMaps folder from 'PC2RAD_inference.py'
    heatmap_output = "./MVTec_Blend_RedBlue_Heatmaps"
    
    generate_ad_heatmaps_v2(original_folder, mask_folder, heatmap_output, item_list, alpha=0.6)